print("Welcome to the tip calculator.\n")
bill = float(input("What was the total bill? $"))
percent = int(input("What percentage tip would ou like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
tip = round(bill * (1 + percent / 100) / people,2)
print(f"Each person should pay: ${tip}")